#!/usr/bin/env bash
set -e              # Exit immediately if a pipeline returns a non-zero status.
set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 

if [[ $# -eq 1 ]] && [[ "$1" = "." ]]; then
    PROJECT=${PWD##*/}
    BRANCH=$(urlencode "$(git branch --show-current)")

    URLS=(
        https://devbuild.arbfund.com/job/"$PROJECT"/job/"$BRANCH"
        https://devbuild.arbfund.com/job/"$PROJECT"-pipeline/job/"$BRANCH"
        https://devbuild.arbfund.com/job/"$PROJECT"
        https://devbuild.arbfund.com/job/"$PROJECT"-pipeline
    )

    # loop through all the urls, and open the first one that returns a 200
    for URL in "${URLS[@]}"; do
        CODE=$(urlexists "$URL")
        echo "$CODE" -- "$URL"
        if [[ "$CODE" = 200 ]]; then
            "$BROWSER" "$URL"
            exit 0
        fi
    done
fi

# if nothing worked, just open the dashboard
"$BROWSER" https://devbuild.arbfund.com
