#!/bin/bash

# if no parameters, then just go to grok
if [[ $# -eq 0 ]]; then
    open https://opengrok.arbfund.com/source/
    exit 0
fi

# if there is a parameter, then search it
open https://opengrok.arbfund.com/source/search\?q="$1"
exit 0