#!/bin/bash

# if [[ $# -eq 1 ]] && [[ "$1" = "?" ]]; then
#   echo "usage: jira"
#   echo "usage: jira FO-123"
#   echo "usage: jira ."
# fi

# if the first argument is "." then pull the Jira case off of the git branch
if [[ $# -eq 1 ]] && [[ "$1" = "." ]]; then
  CASE_NUM=$(git branch --show-current | grep -E -o '\w*-\d+')
  if [[ -n "$CASE_NUM" ]]; then
    open https://jira.arbfund.com/browse/"$CASE_NUM"
    exit 1
  fi
fi

# if an argument is passed in, then go to it
if [[ $# -gt 0 ]]; then
  open https://jira.arbfund.com/browse/"$1"
  exit 1
fi

# punt and just open the dashboard
open https://jira.arbfund.com/secure/Dashboard.jspa