#!/usr/bin/env bash
set -e          # Exit immediately if a pipeline returns a non-zero status.
set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.

# if [[ $# -eq 1 ]] && [[ "$1" = "--help" ]]; then
#   echo "usage: jira"
#   echo "usage: jira FO-123"
#   echo "usage: jira ."
# fi

# if the first argument is "." then pull the Jira case off of the git branch
if [[ $# -eq 1 ]] && [[ $1 == "." ]]; then
	CASE_NUM=$(git branch --show-current | grep -E -o '\w*-\d+' | head -1)
	if [[ -n $CASE_NUM ]]; then
		"$BROWSER" https://cwan.atlassian.net/browse/"$CASE_NUM"
		exit 0
	fi
fi

# if an argument is passed in, then go to it
if [[ $# -gt 0 ]]; then
	"$BROWSER" https://cwan.atlassian.net/browse/"$1"
	exit 0
fi

# punt and just open the dashboard
"$BROWSER" https://cwan.atlassian.net/jira/dashboards/36175
exit 0
