#!/usr/bin/env bash
set -e              # Exit immediately if a pipeline returns a non-zero status.
set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 

# https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html#//apple_ref/doc/uid/10000172i-SW7-SW8

for FILE in "$@"
do
    FILE_LOWER=$(echo "$FILE" | tr '[:upper:]' '[:lower:]')

    # don't recompress the new file
	if [[ "$FILE_LOWER" =~ (-min\.png$) ]]; then exit; fi

    # only compress PNG files
	if [[ ! "$FILE_LOWER" =~ (\.png$) ]]; then exit; fi

	/usr/local/bin/pngquant 32 --skip-if-larger --strip --ext=-min.png -- "$FILE"

    open "${FILE//.PNG/-min.png}"
done
