#!/usr/bin/env bash
set -e              # Exit immediately if a pipeline returns a non-zero status.
set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 

if [[ $# -eq 1 ]] && [[ "$1" = "." ]]; then
    # if parameter is "." then use the current path
    val=${PWD##*/}
    "$BROWSER" https://sonarqube.cwantools.io/dashboard\?id=com.clearwateranalytics:"$val"
elif [[ $# -eq 1 ]]; then
    # just go to the project specified
    "$BROWSER" https://sonarqube.cwantools.io/dashboard\?id=com.clearwateranalytics:"$1"
else
    # punt and go to the top level
    "$BROWSER" https://sonarqube.cwantools.io
fi
