#!/bin/bash

# if no parameter, then just go to stash
if [[ $# -eq 0 ]]; then
    open https://stash.arbfund.com
    exit 0
fi

# if parameter is "." then use the git remote of the current dir
if [[ "$1" = "." ]]; then
    url=$(git remote --verbose | grep -E 'origin.*\(fetch\)')
    [[ "$url" =~ .*7999/(.*)/(.*).git.* ]]
    open https://stash.arbfund.com/projects/"${BASH_REMATCH[1]}"/repos/"${BASH_REMATCH[2]}"/browse

    # at this point, we could go further and go to the current git branch
    #https://stash.arbfund.com/projects/ACCT/repos/aws/browse?at=refs%2Fheads%2Fdave%2FFO-2186-push-early-filter-to-database
    exit 0
fi

# else go to the path passed in
open https://stash.arbfund.com/projects/UI/repos/"$1"/browse
exit 0
