#!/usr/bin/env bash
set -e          # Exit immediately if a pipeline returns a non-zero status.
set -u          # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully.

if [[ $# -eq 1 ]] && [[ $1 == "--help" ]]; then
	echo "NAME"
	echo "  stash --help"
	echo "  stash ."
elif [[ $# -eq 0 ]]; then
	"$BROWSER" https://stash.arbfund.com
elif [[ $1 == "." ]]; then
	# if parameter is "." then use the git remote of the current dir
	url=$(git remote --verbose | grep -E 'origin.*\(fetch\)')
	if [[ $url =~ .*7999/(.*)/(.*).git.* ]]; then
		"$BROWSER" https://stash.arbfund.com/projects/"${BASH_REMATCH[1]}"/repos/"${BASH_REMATCH[2]}"/browse

		# at this point, we could go further and go to the current git branch
		#https://stash.arbfund.com/projects/ACCT/repos/aws/browse?at=refs%2Fheads%2Fdave%2FFO-2186-push-early-filter-to-database
	else
		"$BROWSER" https://stash.arbfund.com
	fi
else
	# go to the path passed in
	"$BROWSER" https://stash.arbfund.com/projects/UI/repos/"$1"/browse
fi
