#!/bin/bash

# if no parameter, then just go to stash
if [[ $# -eq 0 ]]; then
    open https://stash.arbfund.com
    exit 0
fi

# if parameter is "." then use the current path
if [[ "$1" = "." ]]; then
    val=${PWD##*/}
    open https://stash.arbfund.com/projects/UI/repos/"$val"/browse
    exit 0
fi

# else go to the path passed in
open https://stash.arbfund.com/projects/UI/repos/"$1"/browse
exit 0
