#!/usr/bin/env bash
set -e              # Exit immediately if a pipeline returns a non-zero status.
set -u              # Treat unset variables and parameters other than the special parameters ‘@’ or ‘*’ as an error when performing parameter expansion.
set -o pipefail     # Return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands in the pipeline exit successfully. 

MINS=$1
SECONDS=$((MINS * 60))
MESSAGE="Time Up: $MINS minute(s)"

# osascript -e "display notification \"$MESSAGE\" with title \"Timer\"" \

Sleep "$SECONDS"
say 'beep, beep, beep' &
osascript -e "tell application \"System Events\" to display dialog \"$MESSAGE\" with title \"Timer\"" > /dev/null &
